#!/bin/bash

# Display the UID and username of the user executing this script.
# Display if the user is the vagrant user or not

# Display the UID
echo "Your UID is ${UID}"

# Only display if the UID does NOT match 1000
UID_TO_TEST_FOR='1000'

if [[ ${UID} != ${UID_TO_TEST_FOR} ]]
then
	echo "Your UID does not match ${UID_TO_TEST_FOR}"
fi

# Dispplay the username
USER_NAME=$(id -un)

# Test if the command succeded
if [[ "${?}" -ne 0 ]]
then
	echo "The id command did not execute succesfully."
	exit 1
fi

echo "Your username is ${USER_NAME}"

ID_TO_TEST_FOR="parallels"

if [[ "${USER_NAME}" = "${ID_TO_TEST_FOR}" ]]
then
	echo "Your username matches ${ID_TO_TEST_FOR}"
fi
